### ISSUE TITLE
failed to compile - windows 10 , master brach 

### ISSUE THREAD

**Issue by mingqin1** [testing-angular-applications/testing-angular-applications#70]

**Comment by mingqin1** [comment]
Authors:
My environments: windows 10 ; node version v8.9.3; npm version 5.5.1
The code based is master branch.
when I run "ng serve" I got following "webpack: failed to compile"

_C:\openSourceProjects\testing-angular-applications-master\website>ng serve
Your global Angular CLI version (1.7.3) is greater than your local
version (1.6.8). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2018-04-10T02:18:02.524Z
Hash: e42356846415c640ea4b
Time: 2470ms
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 2.94 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 636 bytes [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 41.5 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 855 kB [initial] [rendered]

ERROR in ./node_modules/css-loader?{"sourceMap":false,"import":false}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/sass-loader/lib/loader.js?{"sourceMap":false,"precision":8,"includePaths":[]}!./src/material-app-theme.scss
Module build failed: Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\openSourceProjects\testing-angular-applications-master\website\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at loadLoader (C:\openSourceProjects\testing-angular-applications-master\website\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (C:\openSourceProjects\testing-angular-applications-master\website\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\openSourceProjects\testing-angular-applications-master\website\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\openSourceProjects\testing-angular-applications-master\website\node_modules\loader-runner\lib\LoaderRunner.js:173:18
 @ ./src/material-app-theme.scss 4:14-203
 @ multi ./src/styles.css ./src/material-app-theme.scss
ERROR in Error: No NgModule metadata found for 'AppModule'.
    at NgModuleResolver.resolve (C:\openSourceProjects\testing-angular-applications-master\website\node_modules\@angular\compiler\bundles\compiler.umd.js:20247:23)
    at CompileMetadataResolver.getNgModuleMetadata (C:\openSourceProjects\testing-angular-applications-master\website\node_modules\@angular\compiler\bundles\compiler.umd.js:15216:60)
    at visitLazyRoute (C:\openSourceProjects\testing-angular-applications-master\website\node_modules\@angular\compiler\bundles\compiler.umd.js:31061:104)
    at AotCompiler.listLazyRoutes (C:\openSourceProjects\testing-angular-applications-master\website\node_modules\@angular\compiler\bundles\compiler.umd.js:31029:20)
    at AngularCompilerProgram.listLazyRoutes (C:\openSourceProjects\testing-angular-applications-master\website\node_modules\@angular\compiler-cli\src\transformers\program.js:156:30)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (C:\openSourceProjects\testing-angular-applications-master\website\node_modules\@angular\compiler-cli\src\ngtools_api.js:44:36)
    at AngularCompilerPlugin._getLazyRoutesFromNgtools (C:\openSourceProjects\testing-angular-applications-master\website\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:249:66)
    at Promise.resolve.then.then (C:\openSourceProjects\testing-angular-applications-master\website\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:572:50)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

webpack: Failed to compile._
